baseurl = "https://stevenkoskiblog.netlify.com"
languageCode = "en-us"
title = "Steven Koski's Blog"
# Define how many pages appear per site
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "spf13"
# Enable gogle analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-minimalist-theme"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command

[params]
    site_author = "Steven Koski"
    site_description = "My blog is to tell you all about what I learn in my Intro to Data Science class, as well as keep you updated on my travels across the world."
    location = "Earth"
    # Link custom assets relative to /static
    avatar = "img/profile.jpg"
    header_background = "img/backdrop.jpg"
    header_title = "Steven Koski's Blog"
    copyright = "Powered by [Hugo](http://gohugo.io)."
    custom_css = []
    custom_js  = []

    # Enable gogle analytics by entering your tracking code
    google_analytics = ""

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    linkedin  = ""
    github    = "skoski11"
    gplus     = ""

