---
title: "9.29.2017 Scatterplots"
author: "Steven Koski"
date: '2017-10-02'
slug: 9-29-2017-Scatterplots
tags: R Markdown
categories: R
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
library(Lahman)
library(sqldf)
library(ggplot2)
```

This next code is an example of a scatterplot we learned in class. It gathers all the data and plots thm as dots on a graph to make it easier to visualize the data. We also draw lines between each of the data points to make it easier to visualize how the points are ordered.

```{r}

#This is a scatterplot that has two columns of numerical data and one 
#represents time wile the other reperesents different points of data
query<-"Select playerID, sum(HR) AS Career_HR, sum(SO) AS Career_SO
FROM Batting
GROUP BY playerID
HAVING sum(hr)>=400"

result<-sqldf(query)

ggplot()+
  geom_point(data=result,aes(x=Career_SO,y=Career_HR), size=3)+
ggtitle("Career Strikeout VS Homeruns for Great Hitters")+
xlab("Career Strikeouts")+ ylab("Career Homeruns")
```

